name: macOS x64 Workflow

on:
  workflow_dispatch:

env:
  OPENSSL_VERSION: 3.2.1
  APR_VERSION: 1.7.4
  TCNATIVE_VERSION: 1.3.0
  OPENSSL_INSTALL: ${{ github.workspace }}/build/openssl
  APR_INSTALL: ${{ github.workspace }}/build/apr
  OUTPUT_DIR: ${{ github.workspace }}/lib
  

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Required Libraries with Brew
        run: |
            sudo apt install astyle cmake gcc ninja-build libssl-dev unzip xsltproc doxygen graphviz valgrind

      - name: Run linux.sh
        run: |
          chmod +x linux.sh
          ./linux.sh

      - name: Archive Output Files
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: lib

      - name: Archive Build Files
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: build

      - name: List files
        run: |
          ls -R $OUTPUT_DIR
