name: macOS ARM Workflow

on:
  workflow_dispatch:

env:
  OPENSSL_VERSION: 3.2.1
  APR_VERSION: 1.7.4
  TCNATIVE_VERSION: 1.3.0
  OPENSSL_INSTALL: ${{ github.workspace }}/build/openssl
  APR_INSTALL: ${{ github.workspace }}/build/apr
  OUTPUT_DIR: ${{ github.workspace }}/lib
  

jobs:
  build:
    runs-on: macos-14

    strategy:
      matrix:
        arch: [arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Required Libraries with Brew
        run: |
          brew install ninja doxygen graphviz astyle

      - name: Run macos.sh
        run: |
          chmod +x macos.sh
          ./macos.sh

      - name: Archive Output Files
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: lib

      - name: List files
        run: |
          ls -R $OUTPUT_DIR
