name: macOS ARM Workflow

on:
  workflow_dispatch:

env:
  OPENSSL_VERSION: 3.2.1
  APR_VERSION: 1.7.4
  TCNATIVE_VERSION: 1.3.0
  OPENSSL_INSTALL: ${{ github.workspace }}/build/openssl
  APR_INSTALL: ${{ github.workspace }}/build/apr
  OUTPUT_DIR: ${{ github.workspace }}/bin
  

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        arch: [arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run macos.sh
        run: |
          chmod +x macos.sh
          ./macos.sh

      - name: List files
        run: |
          ls -R  # Add any other commands to access or manipulate the files as needed
